# Generated by Django 4.2.9 on 2024-09-11 09:52

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoMetaData",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_video_title",
                    models.CharField(
                        max_length=220,
                        verbose_name="Custom Video Metadata Title (UUID__title)",
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="Video Title")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Video Description"
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "is_processing",
                    models.BooleanField(default=True, verbose_name="Is Processing"),
                ),
                (
                    "is_processing_completed",
                    models.BooleanField(
                        default=False, verbose_name="Is Processing Completed"
                    ),
                ),
                (
                    "is_processing_failed",
                    models.BooleanField(
                        default=False, verbose_name="Is Processing Failed"
                    ),
                ),
                (
                    "mp4_s3_mpd_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="S3 URL for mp4 MPD file.",
                    ),
                ),
                (
                    "mov_s3_mpd_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="S3 URL for mov MPD file.",
                    ),
                ),
                (
                    "mp4_gcore_cdn_mpd_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="MP4: Gcore CDN URL file.",
                    ),
                ),
                (
                    "mov_gcore_cdn_mpd_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="MOV: Gcore CDN URL MPD file.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Meta Data",
                "verbose_name_plural": "Videos Meta Data",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="event_manag_title_5b80cc_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=6)),
                ("content", models.JSONField()),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="event_manager.videometadata",
                    ),
                ),
            ],
        ),
    ]
