#!/bin/bash 


set -o errexit 


set -o nounset 


python /home/movio/app/manage.py makemigrations --no-input 
python /home/movio/app/manage.py migrate --no-input 
python /home/movio/app/manage.py collectstatic --no-input  --clear 



# the project is running on 9005 port. 
# exec /usr/local/bin/gunicorn movio_api_service.wsgi:application --bind 0.0.0.0:9005 --chdir=/home/movio/app

# For Development
exec /home/movio/app/manage.py runserver 0.0.0.0:9005
