#!/bin/bash 


set -o errexit 


set -o nounset 

# chmod -R 775 ${APP_HOME}/staticfiles

# sudo chown -R movio:movio /home/movio/app
# sudo chmod -R 775 /home/movio/app
# sudo chown -R movio:movio /home/movio/app/staticfiles
# sudo chmod -R 775 /home/movio/app/staticfiles

python /home/movio/app/manage.py makemigrations --no-input 
python /home/movio/app/manage.py migrate --no-input 
python /home/movio/app/manage.py collectstatic --no-input  --clear 



# the project is running on 9005 port. 
exec /usr/local/bin/gunicorn movio_api_service.wsgi:application --bind 0.0.0.0:9005 --chdir=/home/movio/app
